# Copyright 2024 [Your Name]
# Custom Corne workflow for Miryoku ZMK

name: 'Build My Custom Corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2/nrf52840"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      alphas: '["colemak"]'
      extra: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["invertedt"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["#define MIRYOKU_CLIPBOARD_MAC"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'